### ISSUE TITLE
'auth' token display

### ISSUE THREAD

**Issue by mtmorgan** [Jiefei-Wang/GCSConnection#3]
This line seems to be reversed -- if the token exists, shouldn't `token_exist = TRUE` ? https://github.com/Jiefei-Wang/GCSConnection/blob/10518b41ab33b412813636e45c80e3b8f0f09d4c/R/cloud-functions.R#L516

This function https://github.com/Jiefei-Wang/GCSConnection/blob/10518b41ab33b412813636e45c80e3b8f0f09d4c/R/cloud-functions.R#L529 uses "\t" to print, but this is system dependent and not consistent with formatting in other files. Also, the capitalization of the output is inconsistent, sometimes starting with a capital letter 'Billing...', sometimes not 'auth ...'. And generally I think it is better to separate the logic of what to print from the actual print command; a useful idea is to consolidate the output into a single `cat()` statement. So

```
print.auth <- function(x, ...) {
    token <- if (x$token_exist) "******" else ""
    project <- x$billing_project
    if (x$gcloud_auth) {
        source <- "gcloud"
        account <- if (is.null(x$gcloud_account)) "Default" else x$gcloud_account
    } else {
        source <- "JSON file"
        account <- character(0)
    }

    cat(
        "Token:           ", token, "\n",
        "Billing project: ", project, "\n",
        "Auth source:     ", source, "\n",
        if (length(account))
            paste0("Auth account:    ", account, "\n"),
        sep = ""
    )
}
```

**Comment by Jiefei-Wang** [comment]
Forget to close it.
