### ISSUE TITLE
exists_gcloud() does not report correctly

### ISSUE THREAD

**Issue by mtmorgan** [Jiefei-Wang/GCSConnection#4]
https://github.com/Jiefei-Wang/GCSConnection/blob/10518b41ab33b412813636e45c80e3b8f0f09d4c/R/utils.R#L178

The use of Sys.which() seems to be problematic
```
> system2("gcloud", "--version")
Google Cloud SDK 307.0.0
bq 2.0.59
core 2020.08.21
gsutil 4.53
> Sys.which("gcloud")
gcloud
    ""
```
relying on the system environment of the process that launched R, rather than as seen by R -- I modify Sys.getenv("PATH") to included gcloud in .Rprofile

**Comment by Jiefei-Wang** [comment]
Thank you! Can you show me exactly what you have done to the environment variable? I have tried the following but it works fine
```
## Add Documents to PATH
mypath <- Sys.getenv("PATH")
mypath <- paste0(mypath,":/home/jiefei/Documents")
Sys.setenv(PATH= mypath)
## There is a gcs program under the Document path
Sys.which("gcs")
```
Output
```
                         gcs 
"/home/jiefei/Documents/gcs" 
```
The same behavior can be found on Ubuntu 18.04.4 LTS and macOS High Sierra 10.13

Best,
Jiefei

**Comment by mtmorgan** [comment]
```
$ R --vanilla
> Sys.which("gcloud")  # not on path
gcloud
    ""
> system2("gcloud", "--version")
sh: gcloud: command not found
Warning message:
In system2("gcloud", "--version") : error in running command
> Sys.setenv(PATH = paste0("~/bin/google-cloud-sdk/bin:", Sys.getenv("PATH")))  # add gcloud bin to path
> Sys.which("gcloud")  # on modified path, but...
gcloud
    ""
> system2("gcloud", "--version")  # found as expected
Google Cloud SDK 307.0.0
bq 2.0.59
core 2020.08.21
gsutil 4.53
> sessionInfo()
R version 4.0.2 Patched (2020-06-24 r78747)
Platform: x86_64-apple-darwin17.7.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /Users/ma38727/bin/R-4-0-branch/lib/libRblas.dylib
LAPACK: /Users/ma38727/bin/R-4-0-branch/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.0.2
```

**Comment by Jiefei-Wang** [comment]
Thanks. I think the root problem is that you cannot have a `~` in your PATH environment. If you change the environment variable in a terminal, it will do the expansion first and resolve the symbol `~` as your home directory, but it seems like the function `Sys.setenv` treats its argument as a literal string and will not do the expansion for you, so you cannot play the magic like `Sys.setenv(PATH="$PATH:foo")`. To confirm it

R output
```
> Sys.getenv("PATH")
[1] "/usr/bin:/bin:/usr/sbin:/sbin:/Users/jeff/Documents:/usr/local/bin:/Applications/RStudio.app/Contents/MacOS/postback"
> Sys.setenv(PATH= "$PATH:foo")
> Sys.getenv("PATH")
[1] "$PATH:foo"
```

A similar problem can be seen on Linux too. If you use `~`, R even cannot find the program in `system2` function. I do not think this is a bug but I will open a discussion R maillist and add a temporary workaround to the package.

Best,
Jiefei

**Comment by Jiefei-Wang** [comment]
I feel that changing the path to its valid format should be the right solution. If the home symbol `~` presents in PATH, even the `which` command in the terminal cannot find the program. While we can try to run `gcloud` and collect the output to check its existence, it is very slow on my computer. I guess `gcloud` requires network communication when it is called, so this solution is 
 not ideal.

Best,
Jiefei

**Comment by mtmorgan** [comment]
In bash,

```
~$ gcloud --version
-bash: gcloud: command not found
~$ export PATH=~/bin/google-cloud-sdk/bin:$PATH
~$ gcloud --version
Google Cloud SDK 307.0.0
bq 2.0.59
core 2020.08.21
gsutil 4.53
~$ which gcloud
/Users/ma38727/bin/google-cloud-sdk/bin/gcloud
```
but I guess that's because
```
~$ env | grep PATH
PATH=/Users/ma38727/bin/google-cloud-sdk/bin:...
```
ok so I'll attribute this to user error. Thanks for your help.
